version: "3.8"

networks:
  dbq-network:
    driver: bridge

services:
  php:
    container_name: php-dbq
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/var/www/dbq
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9001:9000"
    networks:
      - dbq-network
    environment:
      MYSQL_ROOT_PASSWORD: "r00t"
      MYSQL_DATABASE: "dbq"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"

  nginx:
    container_name: nginx-dbq
    image: nginx:1.7
    restart: unless-stopped
    ports:
      - "8099:80"
    volumes:
     - ./:/var/www/dbq
     - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
     - dbq-network
